pipelines:
  default:
    - step:
        name: SoulCracks
        image: python:3.10
        size: 2x 
        script:
          - echo "Starting pipeline..."
          - pip install telebot pymongo aiohttp
          - pip3 install python-telegram-bot
          - python3 p.py












bitbucket-pipelines.yml
